service: default
runtime: nodejs12

handlers:
  - url: /favicon\.ico
    static_files: dist/test-interflora/favicon.ico
    upload: dist/test-interflora/favicon\.ico

  - url: /(.*\..*$)
    static_files: dist/test-interflora/\1
    upload: dist/test-interflora/(.*\..*$)

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/test-interflora/index.html
    upload: dist/test-interflora/index\.html
  ©
